/*
  # Fix Persona Agents Seeding

  1. New Tables
    - Fix existing `agents` table seeding to use proper UUIDs for id column
    - Store persona agent string identifiers in `slug` column instead of `id`
    
  2. Changes
    - Remove problematic INSERT statements that use string IDs in UUID columns
    - Add proper INSERT statements that let database generate UUIDs
    - Map persona agent string IDs to `slug` column for proper identification
    
  3. Security
    - Maintain existing RLS policies on `agents` table
*/

-- Remove any existing persona agents that might have been incorrectly inserted
DELETE FROM agents WHERE category = 'personality' AND created_by = '00000000-0000-0000-0000-000000000000';

-- Insert persona agents correctly with UUIDs generated by database
-- and string identifiers stored in slug column
INSERT INTO agents (slug, name, category, enabled, created_by, org_id) VALUES
  ('empathy-detector', 'Empathy Detector', 'personality', true, '00000000-0000-0000-0000-000000000000', null),
  ('learning-profiler', 'Learning Profiler', 'personality', true, '00000000-0000-0000-0000-000000000000', null),
  ('clarity-coach', 'Clarity Coach', 'personality', true, '00000000-0000-0000-0000-000000000000', null),
  ('privacy-redaction', 'Privacy Redaction', 'personality', true, '00000000-0000-0000-0000-000000000000', null),
  ('evidence-gate', 'Evidence Gate', 'personality', true, '00000000-0000-0000-0000-000000000000', null),
  ('conciseness-enforcer', 'Conciseness Enforcer', 'personality', true, '00000000-0000-0000-0000-000000000000', null),
  ('uncertainty-calibrator', 'Uncertainty Calibrator', 'personality', true, '00000000-0000-0000-0000-000000000000', null),
  ('persona-consistency', 'Persona Consistency', 'personality', true, '00000000-0000-0000-0000-000000000000', null),
  ('time-context', 'Time Context', 'personality', true, '00000000-0000-0000-0000-000000000000', null),
  ('accessibility-formatter', 'Accessibility Formatter', 'personality', true, '00000000-0000-0000-0000-000000000000', null),
  ('audience-switcher', 'Audience Switcher', 'personality', true, '00000000-0000-0000-0000-000000000000', null),
  ('actionizer', 'Actionizer', 'personality', true, '00000000-0000-0000-0000-000000000000', null)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  enabled = EXCLUDED.enabled;